# Generated by Django 4.2.16 on 2024-09-24 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='stripeCustomerId',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Stripe Customer ID'),
        ),
        migrations.AddField(
            model_name='user',
            name='stripePriceId',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Stripe Price ID'),
        ),
        migrations.AddField(
            model_name='user',
            name='stripeSubscriptionId',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Stripe Subscription ID'),
        ),
        migrations.AddField(
            model_name='user',
            name='stripeSubscriptionStatus',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Stripe Subscription Status'),
        ),
    ]
