# Generated by Django 5.0.6 on 2024-09-20 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('question', models.CharField(help_text='Digite a questão', max_length=255, verbose_name='Questão')),
                ('correct_answer', models.CharField(help_text='Digite a resposta correta', max_length=255, verbose_name='Resposta correta')),
                ('wrong_answer_1', models.CharField(blank=True, help_text='Digite a resposta errada 1', max_length=255, null=True, verbose_name='Resposta errada 1')),
                ('wrong_answer_2', models.CharField(blank=True, help_text='Digite a resposta errada 2', max_length=255, null=True, verbose_name='Resposta errada 2')),
                ('wrong_answer_3', models.CharField(blank=True, help_text='Digite a resposta errada 3', max_length=255, null=True, verbose_name='Resposta errada 3')),
                ('wrong_answer_4', models.CharField(blank=True, help_text='Digite a resposta errada 4', max_length=255, null=True, verbose_name='Resposta errada 4')),
                ('difficulty', models.IntegerField(choices=[(1, 'Muito Fácil'), (2, 'Fácil'), (3, 'Médio'), (3, 'Difícil'), (3, 'Muito Difícil')], help_text='Digite a dificuldade da questão', verbose_name='Dificuldade')),
                ('subject', models.CharField(help_text='Digite a matéria da questão', max_length=255, verbose_name='Matéria')),
                ('year', models.IntegerField(help_text='Digite o ano da questão', verbose_name='Ano')),
                ('university', models.CharField(help_text='Digite a universidade da questão', max_length=255, verbose_name='Universidade')),
            ],
            options={
                'verbose_name': 'Questão',
                'verbose_name_plural': 'Questões',
                'ordering': ['-created_at'],
            },
        ),
    ]
