# Generated by Django 5.1.1 on 2024-09-20 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='question',
            field=models.TextField(help_text='Digite a questão', verbose_name='Questão'),
        ),
    ]
