# Generated by Django 5.1.1 on 2024-09-20 19:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0004_alter_question_wrong_answer_1_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('name', models.CharField(help_text='Digite o nome da matéria', max_length=255, verbose_name='Nome')),
                ('color', models.CharField(blank=True, help_text='Digite a cor da matéria', max_length=255, null=True, verbose_name='Cor')),
                ('description', models.TextField(blank=True, help_text='Digite a descrição da matéria', null=True, verbose_name='Descrição')),
            ],
            options={
                'verbose_name': 'Matéria',
                'verbose_name_plural': 'Matérias',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AlterField(
            model_name='question',
            name='subject',
            field=models.ForeignKey(help_text='Selecione a matéria da questão', on_delete=django.db.models.deletion.CASCADE, to='questions.subject', verbose_name='Matéria'),
        ),
    ]
