# Generated by Django 5.1.1 on 2024-09-20 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0005_subject_alter_question_subject'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='revision',
            field=models.BooleanField(default=False, help_text='Marque se a questão é precisa de uma revisão', verbose_name='Revisão'),
        ),
    ]
