# Generated by Django 5.1.1 on 2024-09-20 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0006_question_revision'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='image',
            field=models.ImageField(blank=True, help_text='Selecione a imagem da questão', null=True, upload_to='questions', verbose_name='Imagem'),
        ),
    ]
