# Generated by Django 4.2.16 on 2024-09-23 12:21

import colorfield.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0009_question_resolution'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subject',
            name='color',
            field=colorfield.fields.ColorField(blank=True, default='#FFFFFF', help_text='Digite a cor da matéria', image_field=None, max_length=25, null=True, samples=None, verbose_name='Cor'),
        ),
    ]
