# Generated by Django 4.2.16 on 2024-09-23 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0010_alter_subject_color'),
    ]

    operations = [
        migrations.CreateModel(
            name='University',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('name', models.CharField(help_text='Digite o nome da universidade', max_length=255, verbose_name='Nome')),
                ('description', models.TextField(blank=True, help_text='Digite a descrição da universidade', null=True, verbose_name='Descrição')),
            ],
            options={
                'verbose_name': 'Universidade',
                'verbose_name_plural': 'Universidades',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AlterField(
            model_name='question',
            name='revision',
            field=models.BooleanField(default=False, help_text='Marque se a questão precisa de uma revisão', verbose_name='Revisão'),
        ),
    ]
