# Generated by Django 4.2.16 on 2024-09-23 12:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0011_university_alter_question_revision'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='university',
            field=models.ForeignKey(help_text='Selecione a universidade da questão', on_delete=django.db.models.deletion.CASCADE, to='questions.university', verbose_name='Universidade'),
        ),
    ]
