# Generated by Django 4.2.16 on 2024-09-23 12:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0012_alter_question_university'),
    ]

    operations = [
        migrations.CreateModel(
            name='Phases',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('name', models.CharField(help_text='Digite o nome da fase', max_length=255, verbose_name='Nome')),
                ('description', models.TextField(blank=True, help_text='Digite a descrição da fase', null=True, verbose_name='Descrição')),
                ('difficulty', models.IntegerField(choices=[(1, 'Muito Fácil'), (2, 'Fácil'), (3, 'Médio'), (3, 'Difícil'), (3, 'Muito Difícil')], help_text='Digite a dificuldade da fase', verbose_name='Dificuldade')),
                ('coins', models.IntegerField(default=0, help_text='Digite a quantidade de moedas da fase', verbose_name='Moedas')),
                ('questions', models.ManyToManyField(blank=True, help_text='Selecione as questões da fase', to='questions.question', verbose_name='Questões')),
                ('subject', models.ForeignKey(help_text='Selecione a matéria da fase', on_delete=django.db.models.deletion.CASCADE, to='questions.subject', verbose_name='Matéria')),
                ('university', models.ForeignKey(help_text='Selecione a universidade da fase', on_delete=django.db.models.deletion.CASCADE, to='questions.university', verbose_name='Universidade')),
            ],
            options={
                'verbose_name': 'Fase',
                'verbose_name_plural': 'Fases',
                'ordering': ['-created_at'],
            },
        ),
    ]
