# Generated by Django 4.2.16 on 2024-09-23 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Plans',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('name', models.CharField(help_text='Nome do plano', max_length=255, unique=True, verbose_name='Nome do plano')),
                ('monthly_price', models.DecimalField(decimal_places=2, help_text='Preço mensal', max_digits=10, verbose_name='Preço mensal')),
                ('description', models.TextField(help_text='Descrição', verbose_name='Descrição')),
                ('is_active', models.BooleanField(default=True, help_text='Ativo', verbose_name='Ativo')),
            ],
            options={
                'verbose_name': 'Plano',
                'verbose_name_plural': 'Planos',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('name', models.CharField(help_text='Nome do produto', max_length=255, verbose_name='Nome do produto')),
                ('description', models.TextField(help_text='Descrição', verbose_name='Descrição')),
                ('price', models.DecimalField(decimal_places=2, help_text='Preço', max_digits=10, verbose_name='Preço')),
                ('is_active', models.BooleanField(default=True, help_text='Ativo', verbose_name='Ativo')),
            ],
            options={
                'verbose_name': 'Produto',
                'verbose_name_plural': 'Produtos',
                'ordering': ['-created_at'],
            },
        ),
    ]
