# Generated by Django 4.2.16 on 2024-09-24 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0003_products_next_due_date_products_stripe_price_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='products',
            name='next_due_date',
        ),
        migrations.RemoveField(
            model_name='products',
            name='stripe_price_id',
        ),
        migrations.RemoveField(
            model_name='products',
            name='stripe_subscription_id',
        ),
        migrations.AddField(
            model_name='plans',
            name='next_due_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='plans',
            name='stripe_price_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='plans',
            name='stripe_subscription_id',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
    ]
